#!/usr/bin/env python3
"""
State CSV Plotter — Interactive Matplotlib Viewer
=================================================
Reads a CSV file generated by state_plot_node and plots Ground Truth vs EKF.
Allows you to zoom and pan interactively.

USAGE:
    python3 plot_state_csv.py [path_to_csv]

If no path is provided, it will automatically find the most recent
state_plot_*.csv file in your home directory.
"""

import sys
import os
import glob
import csv
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# ── colour palette ────────────────────────────────────────────────────────────
C_GT  = '#2196F3'   # blue
C_EKF = '#4CAF50'   # green

def find_latest_csv():
    """Finds the most recent state_plot_*.csv in the home directory."""
    search_pattern = os.path.expanduser('~/state_plot_*.csv')
    files = glob.glob(search_pattern)
    if not files:
        return None
    # Sort by modification time, descending
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]

def load_csv(filepath):
    """Loads the CSV data into a dictionary of numpy arrays."""
    data = {
        't': [],
        'gt_x': [], 'gt_y': [], 'gt_yaw': [], 'gt_vel': [],
        'ekf_x': [], 'ekf_y': [], 'ekf_yaw': [], 'ekf_vel': []
    }
    
    with open(filepath, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not row['time_s']:
                continue
            
            data['t'].append(float(row['time_s']))
            
            # Ground truth
            data['gt_x'].append(float(row['gt_x_m']) if row['gt_x_m'] else np.nan)
            data['gt_y'].append(float(row['gt_y_m']) if row['gt_y_m'] else np.nan)
            data['gt_yaw'].append(float(row['gt_yaw_deg']) if row['gt_yaw_deg'] else np.nan)
            data['gt_vel'].append(float(row['gt_vel_ms']) if row['gt_vel_ms'] else np.nan)
            
            # EKF estimate
            data['ekf_x'].append(float(row['ekf_x_m']) if row['ekf_x_m'] else np.nan)
            data['ekf_y'].append(float(row['ekf_y_m']) if row['ekf_y_m'] else np.nan)
            data['ekf_yaw'].append(float(row['ekf_yaw_deg']) if row['ekf_yaw_deg'] else np.nan)
            data['ekf_vel'].append(float(row['ekf_vel_ms']) if row['ekf_vel_ms'] else np.nan)

    # Convert to numpy arrays
    for k in data:
        data[k] = np.array(data[k])
        
    return data

def build_interactive_plot(data, filename):
    """Creates the interactive matplotlib figure."""
    BG = '#1a1a2e'
    AX = '#16213e'
    GR = '#0f3460'

    plt.rcParams.update({
        'font.family': 'DejaVu Sans',
        'font.size': 10,
        'axes.facecolor': AX,
        'figure.facecolor': BG,
        'axes.edgecolor': '#4a4a7a',
        'axes.labelcolor': '#c0c0e0',
        'xtick.color': '#8080a0',
        'ytick.color': '#8080a0',
        'grid.color': GR,
        'grid.linewidth': 0.6,
        'text.color': '#e0e0ff',
        'legend.facecolor': '#0f0f2a',
        'legend.edgecolor': '#4a4a7a',
        'legend.fontsize': 9,
    })

    fig = plt.figure(figsize=(16, 9), facecolor=BG)
    fig.canvas.manager.set_window_title(f"State Plot Viewer: {os.path.basename(filename)}")
    fig.suptitle(f'Vehicle State Analysis\nData: {os.path.basename(filename)}',
                 color='#e0e0ff', fontsize=14, fontweight='bold', y=0.98)

    # 2 rows, 3 columns
    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.35, wspace=0.3,
                           left=0.06, right=0.97, top=0.90, bottom=0.07)

    ax_traj = fig.add_subplot(gs[0, 0])
    ax_x    = fig.add_subplot(gs[0, 1])
    ax_y    = fig.add_subplot(gs[0, 2], sharex=ax_x)    # Link X axes for time series
    ax_yaw  = fig.add_subplot(gs[1, 0], sharex=ax_x)
    ax_vel  = fig.add_subplot(gs[1, 1], sharex=ax_x)
    ax_err  = fig.add_subplot(gs[1, 2], sharex=ax_x)

    axes = [ax_traj, ax_x, ax_y, ax_yaw, ax_vel, ax_err]

    # ---- Plotting functions ----
    t = data['t']

    # 1. Trajectory
    ax_traj.plot(data['gt_x'], data['gt_y'], color=C_GT, label='Ground Truth', lw=2.0)
    ax_traj.plot(data['ekf_x'], data['ekf_y'], color=C_EKF, label='EKF Estimate', lw=1.8, linestyle='--', alpha=0.8)
    ax_traj.set_title('XY Trajectory', color='#c0c0ff')
    ax_traj.set_xlabel('X [m]')
    ax_traj.set_ylabel('Y [m]')
    ax_traj.axis('equal')
    ax_traj.legend()

    # 2. X vs Time
    ax_x.plot(t, data['gt_x'], color=C_GT, label='GT', lw=2.0)
    ax_x.plot(t, data['ekf_x'], color=C_EKF, label='EKF', lw=1.8, linestyle='--', alpha=0.8)
    ax_x.set_title('X Position vs Time', color='#c0c0ff')
    ax_x.set_ylabel('X [m]')

    # 3. Y vs Time
    ax_y.plot(t, data['gt_y'], color=C_GT, label='GT', lw=2.0)
    ax_y.plot(t, data['ekf_y'], color=C_EKF, label='EKF', lw=1.8, linestyle='--', alpha=0.8)
    ax_y.set_title('Y Position vs Time', color='#c0c0ff')
    ax_y.set_ylabel('Y [m]')

    # 4. Yaw vs Time
    ax_yaw.plot(t, data['gt_yaw'], color=C_GT, label='GT', lw=2.0)
    ax_yaw.plot(t, data['ekf_yaw'], color=C_EKF, label='EKF', lw=1.8, linestyle='--', alpha=0.8)
    ax_yaw.set_title('Yaw vs Time', color='#c0c0ff')
    ax_yaw.set_ylabel('Yaw [°]')
    ax_yaw.set_xlabel('Time [s]')

    # 5. Velocity vs Time
    ax_vel.plot(t, data['gt_vel'], color=C_GT, label='GT', lw=2.0)
    ax_vel.plot(t, data['ekf_vel'], color=C_EKF, label='EKF', lw=1.8, linestyle='--', alpha=0.8)
    ax_vel.set_title('Velocity vs Time', color='#c0c0ff')
    ax_vel.set_ylabel('V [m/s]')
    ax_vel.set_xlabel('Time [s]')

    # 6. Error vs Time
    pos_error = np.sqrt((data['gt_x'] - data['ekf_x'])**2 + (data['gt_y'] - data['ekf_y'])**2)
    ax_err.plot(t, pos_error, color='#ff5555', label='Position Error', lw=1.5)
    ax_err.set_title('EKF Position Error vs GT', color='#c0c0ff')
    ax_err.set_ylabel('Error [m]')
    ax_err.set_xlabel('Time [s]')
    ax_err.legend()

    # ---- Styling all axes ----
    for ax in axes:
        ax.grid(True, alpha=0.4)
        for spine in ax.spines.values():
            spine.set_edgecolor('#4a4a7a')
        if ax != ax_traj and ax != ax_err:
            ax.legend()

    plt.show()

def main():
    if len(sys.argv) > 1:
        filepath = sys.argv[1]
    else:
        print("No CSV file provided, looking for the most recent one...")
        filepath = find_latest_csv()
        if not filepath:
            print("Error: Could not find any state_plot_*.csv files in your home directory.")
            print("Please provide the path manually: python3 plot_state_csv.py /path/to/file.csv")
            sys.exit(1)
            
    print(f"Loading data from: {filepath}")
    
    if not os.path.exists(filepath):
        print(f"Error: File '{filepath}' does not exist.")
        sys.exit(1)
        
    try:
        data = load_csv(filepath)
        num_points = len(data['t'])
        print(f"Successfully loaded {num_points} data points.")
        print("Opening interactive plot window. Use the toolbar at the bottom to zoom/pan.")
        build_interactive_plot(data, filepath)
    except Exception as e:
        print(f"An error occurred while plotting: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
